apiVersion: v1
kind: Secret
metadata:
  name: ping-smart-club-secret
  namespace: default
type: Opaque
stringData:
  db.user: "root"
  db.password: "root"
  redis.password: ""
  rabbitmq.user: "admin"
  rabbitmq.password: "admin123"
